### ISSUE TITLE
Найти хостинг для БД

### ISSUE THREAD

**Issue by gal20040** [gal20040/DMDFall2016Project#5]

**Comment by WestCoast5550** [comment]
Я ПИЛЮ!!!

**Comment by gal20040** [comment]
коммент с ваффли!

**Comment by WestCoast5550** [comment]
КОМЕНТ С ГИТА!

**Comment by gal20040** [comment]
вариант: https://sprinthost.ru/

**Comment by gal20040** [comment]
Я так понял, что хостинг нам не нужен: во-перых со слов Гарцева я понял, что надо показывать приложение, работающее локально, а во вторых можно подключиться удалённо к компу и юзать с него приложение.
Ставлю приоритет низкий.

**Comment by gal20040** [comment]
Не требуется делать - закрываю.
